[build]
  command = "yarn workspace @nulogy/components build && yarn workspace @nulogy/docs build"
  publish = "docs/public"

[build.environment]
  YARN_VERSION = "1.13.0"

[context.storybook]
  command = "yarn workspace @nulogy/components build-storybook"
  publish = "components/storybook-static"

