[build]
  command = "yarn workspace @nulogy/components build && yarn workspace @nulogy/docs build"
  publish = "docs/public"

[build.environment]
#   NODE_VERSION = "10.15.0"
#   YARN_VERSION = "1.13.0"