[build]
  command = "yarn run build-docs"
  publish = "docs/dist"

# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
